# Generated by Django 6.0.5 on 2026-08-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='jobs.jobposting'),
        ),
    ]
