# Generated by Django 6.1 on 2026-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobseekerprofile_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('JOB_SEEKER', 'Job Seeker'), ('ADMIN', 'Admin')], default='JOB_SEEKER', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
