# Generated by Django 6.0.5 on 2026-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_delete_employerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPoolCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short Introduction')),
                ('skills', models.CharField(blank=True, help_text='Comma separated skills', max_length=255)),
                ('cv_file', models.FileField(upload_to='private_media/cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
    ]
